//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 09:48:20 AM CEST 
//


package de.stetro.matin.dbw.prak1.entities.employees;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for currenttype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="currenttype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="euro"/>
 *     &lt;enumeration value="dollar"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "currenttype")
@XmlEnum
public enum Currenttype {

    @XmlEnumValue("euro")
    EURO("euro"),
    @XmlEnumValue("dollar")
    DOLLAR("dollar");
    private final String value;

    Currenttype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Currenttype fromValue(String v) {
        for (Currenttype c: Currenttype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
